version: 2.1

commands:
  setup:
    steps:
      - checkout
      - run: emacs --version

  install:
    steps:
      - run: make install
  lint:
    steps:
      - run: make lint
  test:
    steps:
      - run: make test
jobs:
  test:
    docker:
      - image: schmir/emacs-zimports-test
    steps:
      - setup
      - install
      - lint
      - test

workflows:
  version: 2
  default:
    jobs:
      - test
